name: Publish library on TestPyPI and DockerHub

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Lint, Build and Test the library
    uses: ./.github/workflows/build-test.yml

  dockerhub:
    name: Upload image to DockerHub
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

      - uses: actions/checkout@v3

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download built library
        uses: actions/download-artifact@v3
        with:
          name: built-library
          path: dist

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .github/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/biclustlib:latest, ${{ secrets.DOCKERHUB_USERNAME }}/biclustlib:${{ steps.extract_branch.outputs.branch }}

  testpypi:
    name: Publish the library on TestPyPI
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Download built library
        uses: actions/download-artifact@v3
        with:
          name: built-library
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  notify:
    name: Send notification to Telegram
    needs: [ check, dockerhub, testpypi ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"

      - uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_TO }}
          message: |
            New release ${{ steps.extract_branch.outputs.branch }} in ${{ github.repository }}
            Author: ${{ github.actor }}
            
            Build-Test status: ${{ needs.check.result }}
            Docker status: ${{ needs.dockerhub.result }}
            TestPyPI status: ${{ needs.testpypi.result }}
